
const EVENTS = {
  REQ_START_GAME: "req-start-game",
  REQ_CANCEL_GAME:"req-cancel-game",
  RES_CANCEL_GAME: "res-cancel-game",
  REQ_USER_JOIN: "req-user-join",
  RES_USER_JOINED: "res-user-joined",
  REQ_USER_DELETE: "req-user-delete",
  RES_USER_DELETED: "res-user-deleted",
  NOTIFICATIONS:"notifications",
  NOTIFICATIONS_TEST:"notifications-test",
  REQ_TITLE_CHANGE: "req-title-change",
  RES_TITLE_CHANGED: "res-title-changed",
  REQ_ROOM_CHECK: "req-room-check",
  REQ_ISSUE_ADD: "req-issue-add",
  REQ_ISSUE_DELETE: "req-issue-delete",
  REQ_ISSUE_UPDATE:"req-issue-update",
  RES_ISSUES_GET:"res-issues-get",
  REQ_ISSUES_GET:"req-issues-get",
  REQ_START_POKER: "req-start-poker",
  RES_START_POKER: "res-start-poker",
  REQ_END_POKER:"req-end-poker",
  RES_END_POKER:"res-end-poker",
  REQ_START_VOTE: "req-start-vote",
  RES_START_VOTE:"res-start-vote",
  REQ_RESULT_VOTE:"req-result-vote",
  RES_RESULT_VOTE:"res-result-vote",
  REQ_MESSAGE_ADD:"req-message-add",
  RES_MESSAGES_GET:"res-messages-get",
  REQ_MESSAGES_GET:"req-messages-get",
  REQ_SELECT_ISSUE: "req-select-issue",
  RES_SELECT_ISSUE: 'res-select-issue',
  REQ_START_ROUND: 'req-start-round',
  RES_START_ROUND: 'res-start-round',
  REQ_FINISH_ROUND: 'req-finish-round',
  RES_FINISH_ROUND: 'res-finish-round',
  REQ_SET_SCORE: 'req-set-score',
  RES_SET_SCORE: 'res-set-score',
  REQ_TEST: "req-test",
  RES_TEST:"res-test",
  REQ_USER_GAME_JOIN: "req-user-game-join",
  RES_USER_ADMIT: "res-user-admit",
  REQ_USER_ADMIT: "req-user-admit",
  RES_USER_REJECTED: "res-user-rejected",
  REQ_ROUND_VOTE: "req-round-vote",
  RES_ROUND_VOTE: "res-round-vote",
  REQ_CARDS_FLIP: 'req-cards-flip',
  RES_CARDS_FLIP: 'res-cards-flip',
  REQ_FINISH_GAME: 'req-finish-game',
  RES_FINISH_GAME: 'res-finish-game',
  REQ_CLEAR_VOTING: 'req-clear-voting',

}
export default EVENTS;